engines:
  eslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
   paths:
   - "**.js"
exclude_paths:
- "gulpfile.js"
- "README.md"
- "package.json"
- "test/**/*"
